language: ruby

cache: bundler

before_install:
  - gem install bundler

before_script:
  - bundle update

script:
  - bundle exec rspec

rvm:
  - 2.1.2
  - 2.2.2
  - 2.4.1
  - 2.5.0

gemfile:
  - gemfiles/rails_3.0.gemfile
  - gemfiles/rails_3.1.gemfile
  - gemfiles/rails_3.2.gemfile
  - gemfiles/rails_4.0.gemfile
  - gemfiles/rails_4.1.gemfile
  - gemfiles/rails_4.2.gemfile
  - gemfiles/rails_5.0_sqlite3.gemfile
  - gemfiles/rails_5.0_mysql2.gemfile
  - gemfiles/rails_5.0_pg.gemfile
  - gemfiles/rails_5.1.gemfile

matrix:
  exclude:
  - rvm: 2.1.2
    gemfile: gemfiles/rails_5.0_sqlite3.gemfile
  - rvm: 2.1.2
    gemfile: gemfiles/rails_5.0_mysql2.gemfile
  - rvm: 2.1.2
    gemfile: gemfiles/rails_5.0_pg.gemfile
  - rvm: 2.1.2
    gemfile: gemfiles/rails_5.1.gemfile

  - rvm: 2.2.2
    gemfile: gemfiles/rails_3.0.gemfile
  - rvm: 2.2.2
    gemfile: gemfiles/rails_3.1.gemfile

  - rvm: 2.4.1
    gemfile: gemfiles/rails_3.0.gemfile
  - rvm: 2.4.1
    gemfile: gemfiles/rails_3.1.gemfile
  - rvm: 2.4.1
    gemfile: gemfiles/rails_3.2.gemfile
  - rvm: 2.4.1
    gemfile: gemfiles/rails_4.0.gemfile
  - rvm: 2.4.1
    gemfile: gemfiles/rails_4.1.gemfile
  - rvm: 2.4.1
    gemfile: gemfiles/rails_4.2.gemfile

  - rvm: 2.5.0
    gemfile: gemfiles/rails_3.0.gemfile
  - rvm: 2.5.0
    gemfile: gemfiles/rails_3.1.gemfile
  - rvm: 2.5.0
    gemfile: gemfiles/rails_3.2.gemfile
  - rvm: 2.5.0
    gemfile: gemfiles/rails_4.0.gemfile
  - rvm: 2.5.0
    gemfile: gemfiles/rails_4.1.gemfile
  - rvm: 2.5.0
    gemfile: gemfiles/rails_4.2.gemfile
